image: node:latest

stages:
  - test
  - build

test:
  stage: test
  script:
    - npm install
    - npm run lint

pages:
  stage: build
  script:
    - npm install
    - rm next.config.js
    - mv next.config.gitlab.js next.config.js
    - npm run export
    - rm -rf public
    - mkdir public
    - mv out/* public; true
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
