image: registry.hub.docker.com/library/nodejs:19-alpine3.15

stages:
  - test
  - build

test:
  stage: test
  script:
    - npm install
    - npm run lint

build:
  stage: build
  script:
    - npm instll
    - next build && next export
  artifacts:
    paths:
      - out
