import Head from 'next/head'

import Task from '../components/task';


export default function Home() {

  const notes = 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.';

  const cards = [
    {key: 'target', name: 'Target', color: 'border-[#e13881]'},
    {key: 'contacted', name: 'Contacted', color: 'border-[#3788b1]'},
    {key: 'firstMeeting', name: 'First Meeting', color: 'border-[#aba3c0]'},
  ]

  const tasks = [
    {
      status: 'target',
      title: 'Kevin M',
      url: 'kevin.xyz',
      contacts : [
        {
          name: 'Hannah',
          image: 'contact-1.png'
        },
        {
          name: 'Jack',
          image: 'contact-2.png'
        }
      ],
      last_activity: 'None',
      upcoming: 'None',
      reminder: 'Tomorrow',
      notes : notes
    },
    {
      status: 'contacted',
      title: 'George M',
      url: 'george.xyz',
      contacts : [
        {
          name: 'Hannah',
        },
      ],
      last_activity: 'None',
      upcoming: 'None',
      reminder: 'Tomorrow',
      notes : notes
    },
    {
      status: 'target',
      title: 'Norris',
      url: 'kevin.xyz',
      contacts : [
        {
          name: 'Smith',
        },
        {
          name: 'Jack',
        }
      ],
      last_activity: 'None',
      upcoming: 'None',
      reminder: 'Tomorrow',
      notes : notes
    },
    {
      status: 'firstMeeting',
      title: 'Norris',
      url: 'kevin.xyz',
      last_activity: 'None',
      upcoming: 'None',
      reminder: 'Tomorrow',
      notes : notes
    }
  ]

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className={'grid grid-cols-4 bg-[#f9f5f3]'}>
        {cards.map((cardData, i)=>(
          <div className={'p-3 mb-5'} key={i}>
            <div className={`bg-[#fcfaf8] drop-shadow-md p-3 text-center border-b-4 ${cardData.color} mb-5`}>
              <h2 className={'font-bold text-black'}>{cardData.name}</h2>
            </div>

            <div className="grid gap-6">
              {tasks.filter(item => (item.status === cardData.key)).map((taskData, j)=>(
                <Task taskData={taskData} key={i}/>
              ))}
            </div>
          </div>
        ))}
      </div>

    </div>
  )
}
